import type { DayOfWeek, Routines } from './types';

export const BENGALI_DAYS: Record<DayOfWeek, string> = {
  saturday: 'শনিবার',
  sunday: 'রবিবার',
  monday: 'সোমবার',
  tuesday: 'মঙ্গলবার',
  wednesday: 'বুধবার',
  thursday: 'বৃহস্পতিবার',
  friday: 'শুক্রবার',
};

export const BENGALI_DAYS_POSSESSIVE: Record<DayOfWeek, string> = {
  saturday: 'শনিবারের',
  sunday: 'রবিবারের',
  monday: 'সোমবারের',
  tuesday: 'মঙ্গলবারের',
  wednesday: 'বুধবারের',
  thursday: 'বৃহস্পতিবারের',
  friday: 'শুক্রবারের',
};

export const BENGALI_DAYS_SHORT: Record<DayOfWeek, string> = {
  saturday: 'শনি',
  sunday: 'রবি',
  monday: 'সোম',
  tuesday: 'মঙ্গল',
  wednesday: 'বুধ',
  thursday: 'বৃহঃ',
  friday: 'শুক্র',
};

export const DAY_ORDER: DayOfWeek[] = ['sunday', 'monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday'];


export const INITIAL_ROUTINES: Routines = {
  saturday: [
    { time: '6:00 – 6:15 AM', activity: 'ঘুম থেকে ওঠা + ফ্রেশ' },
    { time: '6:15 – 7:15 AM', activity: 'হালকা পড়াশোনা / রিভিউ' },
    { time: '7:15 – 8:00 AM', activity: 'নাস্তা' },
    { time: '8:00 – 9:30 AM', activity: 'নতুন স্কিল শেখা' },
    { time: '9:30 – 10:00 AM', activity: 'ইংরেজি শেখা' },
    { time: '10:00 – 11:00 AM', activity: 'YouTube ভিডিও তৈরি' },
    { time: '11:00 – 1:00 PM', activity: 'বই পড়া / রিভিশন' },
    { time: '1:00 – 3:00 PM', activity: 'লাঞ্চ + বিকেলের ন্যাপ' },
    { time: '3:30 – 5:00 PM', activity: 'স্কিল প্যাকটিস / প্রজেক্ট' },
    { time: '5:00 – 6:20 PM', activity: 'নতুন স্কিল শেখা' },
    { time: '6:30 – 10:00 PM', activity: 'গভীর পড়াশোনা / প্রজেক্ট' },
    { time: '10:00 – 10:30 PM', activity: 'রিল্যাক্স / ফ্রি টাইম' },
    { time: '11:00 PM', activity: 'ঘুম' },
  ],
  sunday: [
    { time: '6:00 – 6:15 AM', activity: 'ঘুম থেকে ওঠা + ফ্রেশ' },
    { time: '6:15 – 7:15 AM', activity: 'হালকা পড়াশোনা / রিভিউ' },
    { time: '7:15 – 8:00 AM', activity: 'নাস্তা' },
    { time: '8:00 – 9:30 AM', activity: 'নতুন স্কিল শেখা' },
    { time: '9:30 – 10:00 AM', activity: 'ইংরেজি শেখা' },
    { time: '10:00 – 11:00 AM', activity: 'YouTube ভিডিও তৈরি' },
    { time: '11:00 – 1:00 PM', activity: 'বই পড়া / রিভিশন' },
    { time: '1:00 – 3:00 PM', activity: 'লাঞ্চ + বিকেলের ন্যাপ' },
    { time: '3:30 – 5:00 PM', activity: 'স্কিল প্যাকটিস / প্রজেক্ট' },
    { time: '5:00 – 6:20 PM', activity: 'নতুন স্কিল শেখা' },
    { time: '6:30 – 10:00 PM', activity: 'গভীর পড়াশোনা / প্রজেক্ট' },
    { time: '10:00 – 10:30 PM', activity: 'রিল্যাক্স / ফ্রি টাইম' },
    { time: '11:00 PM', activity: 'ঘুম' },
  ],
  monday: [
    { time: '6:00 – 6:15 AM', activity: 'ঘুম থেকে ওঠা + ফ্রেশ' },
    { time: '6:15 – 7:15 AM', activity: 'হালকা পড়াশোনা / রিভিউ' },
    { time: '7:15 – 7:30 AM', activity: 'নাস্তা' },
    { time: '7:30 AM – 2:30 PM', activity: 'কলেজ (Principle of Finance, Management, Principle of Accounting, History of Bangladesh, Introduction to Business + ব্রেক)' },
    { time: '2:30 – 3:00 PM', activity: 'গোসল + ফ্রেশ' },
    { time: '3:00 – 3:30 PM', activity: 'লাঞ্চ' },
    { time: '3:30 – 4:30 PM', activity: 'কলেজের পড়া রিভিশন' },
    { time: '4:30 – 5:00 PM', activity: 'হালকা বিরতি / চা' },
    { time: '5:00 – 6:20 PM', activity: 'নতুন স্কিল শেখা (ICT / প্রজেক্ট)' },
    { time: '6:30 – 7:30 PM', activity: 'Marketing – গভীর পড়াশোনা' },
    { time: '7:30 – 8:15 PM', activity: 'Finance – গভীর পড়াশোনা' },
    { time: '8:15 – 8:20 PM', activity: 'হালকা বিরতি' },
    { time: '8:20 – 9:00 PM', activity: 'Accounting – গভীর পড়াশোনা' },
    { time: '9:00 – 9:40 PM', activity: 'Introduction to Business – গভীর পড়াশোনা' },
    { time: '9:40 – 10:30 PM', activity: 'Economics / Project – প্রয়োগ' },
    { time: '10:30 – 11:00 PM', activity: 'রিল্যাক্স / ফ্রি টাইম' },
    { time: '11:00 PM', activity: 'ঘুম' },
  ],
  tuesday: [
    { time: '6:00 – 6:15 AM', activity: 'ঘুম থেকে ওঠা + ফ্রেশ' },
    { time: '6:15 – 7:15 AM', activity: 'হালকা পড়াশোনা / রিভিউ' },
    { time: '7:15 – 7:30 AM', activity: 'নাস্তা' },
    { time: '7:30 AM – 2:30 PM', activity: 'কলেজ (Marketing, Finance, Accounting, Economics, ICT + ব্রেক)' },
    { time: '2:30 – 3:00 PM', activity: 'গোসল + ফ্রেশ' },
    { time: '3:00 – 3:30 PM', activity: 'লাঞ্চ' },
    { time: '3:30 – 4:30 PM', activity: 'কলেজের পড়া রিভিশন' },
    { time: '4:30 – 5:00 PM', activity: 'হালকা বিরতি / চা / হাঁটা' },
    { time: '5:00 – 6:20 PM', activity: 'নতুন স্কিল শেখা (ICT / প্রজেক্ট)' },
    { time: '6:30 – 7:30 PM', activity: 'Marketing – গভীর পড়াশোনা' },
    { time: '7:30 – 8:15 PM', activity: 'Finance – গভীর পড়াশোনা' },
    { time: '8:15 – 8:20 PM', activity: 'হালকা বিরতি' },
    { time: '8:20 – 9:00 PM', activity: 'Management – গভীর পড়াশোনা' },
    { time: '9:00 – 9:40 PM', activity: 'Marketing – গভীর পড়াশোনা' },
    { time: '9:40 – 10:30 PM', activity: 'Project / Skill প্রয়োগ' },
    { time: '10:30 – 11:00 PM', activity: 'রিল্যাক্স / ফ্রি টাইম' },
    { time: '11:00 PM', activity: 'ঘুম' },
  ],
  wednesday: [
    { time: '6:00 – 6:15 AM', activity: 'ঘুম থেকে ওঠা + ফ্রেশ' },
    { time: '6:15 – 7:15 AM', activity: 'হালকা পড়াশোনা / রিভিউ' },
    { time: '7:15 – 7:30 AM', activity: 'নাস্তা' },
    { time: '8:30 AM – 2:30 PM', activity: 'কলেজ (Accounting, Finance, Management, Marketing + ব্রেক)' },
    { time: '2:30 – 3:00 PM', activity: 'গোসল + ফ্রেশ' },
    { time: '3:00 – 3:30 PM', activity: 'লাঞ্চ' },
    { time: '3:30 – 4:30 PM', activity: 'কলেজের পড়া রিভিশন' },
    { time: '4:30 – 5:00 PM', activity: 'হালকা বিরতি / চা' },
    { time: '5:00 – 6:20 PM', activity: 'নতুন স্কিল শেখা' },
    { time: '6:30 – 7:30 PM', activity: 'Accounting – গভীর পড়াশোনা' },
    { time: '7:30 – 8:15 PM', activity: 'Finance – গভীর পড়াশোনা' },
    { time: '8:15 – 8:20 PM', activity: 'হালকা বিরতি' },
    { time: '8:20 – 9:00 PM', activity: 'Management – গভীর পড়াশোনা' },
    { time: '9:00 – 9:40 PM', activity: 'Marketing – গভীর পড়াশোনা' },
    { time: '9:40 – 10:30 PM', activity: 'Project / Skill প্রয়োগ' },
    { time: '10:30 – 11:00 PM', activity: 'রিল্যাক্স / ফ্রি টাইম' },
    { time: '11:00 PM', activity: 'ঘুম' },
  ],
  thursday: [
    { time: '6:00 – 6:15 AM', activity: 'ঘুম থেকে ওঠা + ফ্রেশ' },
    { time: '6:15 – 7:15 AM', activity: 'হালকা পড়াশোনা / রিভিউ' },
    { time: '7:15 – 7:30 AM', activity: 'নাস্তা' },
    { time: '7:30 AM – 2:30 PM', activity: 'কলেজ (ICT, Finance, Accounting, Introduction to Business, Economics + ব্রেক)' },
    { time: '2:30 – 3:00 PM', activity: 'গোসল + ফ্রেশ' },
    { time: '3:00 – 3:30 PM', activity: 'লাঞ্চ' },
    { time: '3:30 – 4:30 PM', activity: 'কলেজের পড়া রিভিশন' },
    { time: '4:30 – 5:00 PM', activity: 'হালকা বিরতি / চা / হাঁটা' },
    { time: '5:00 – 6:20 PM', activity: 'নতুন স্কিল শেখা' },
    { time: '6:30 – 7:30 PM', activity: 'ICT – গভীর পড়াশোনা' },
    { time: '7:30 – 8:15 PM', activity: 'Finance – গভীর পড়াশোনা' },
    { time: '8:15 – 8:20 PM', activity: 'হালকা বিরতি' },
    { time: '8:20 – 9:00 PM', activity: 'Accounting – গভীর পড়াশোনা' },
    { time: '9:00 – 9:40 PM', activity: 'Introduction to Business – গভীর পড়াশোনা' },
    { time: '9:40 – 10:30 PM', activity: 'Economics / Project – প্রয়োগ' },
    { time: '10:30 – 11:00 PM', activity: 'রিল্যাক্স / ফ্রি টাইম' },
    { time: '11:00 PM', activity: 'ঘুম' },
  ],
  friday: [
    { time: '6:00 – 6:15 AM', activity: 'ঘুম থেকে ওঠা + ফ্রেশ' },
    { time: '6:15 – 7:15 AM', activity: 'হালকা পড়া / হালকা রিভিউ' },
    { time: '7:15 – 8:00 AM', activity: 'নাস্তা' },
    { time: '8:00 – 9:30 AM', activity: 'নতুন স্কিল শেখা' },
    { time: '9:30 – 10:00 AM', activity: 'ইংরেজি শেখা' },
    { time: '10:00 – 11:00 AM', activity: 'YouTube ভিডিও তৈরি' },
    { time: '11:00 – 12:45 PM', activity: 'লাঞ্চ + গোসল + Jumma Namaz' },
    { time: '1:00 – 2:30 PM', activity: 'বই পড়া / রিভিশন' },
    { time: '3:00 – 3:30 PM', activity: 'হালকা ন্যাপ / বিশ্রাম' },
    { time: '3:30 – 5:00 PM', activity: 'স্কিল প্যাকটিস / প্রজেক্ট' },
    { time: '5:00 – 6:20 PM', activity: 'বই পড়া / নতুন স্কিল প্রয়োগ' },
    { time: '6:30 – 7:30 PM', activity: 'গভীর পড়াশোনা' },
    { time: '10:00 – 10:30 PM', activity: 'রিল্যাক্স / হালকা ইউটিউব / গান' },
    { time: '11:00 PM', activity: 'ঘুম' },
  ],
};

export const INITIAL_CHECKLIST_ITEMS = [
  { id: 'cl-1', task: 'সকালে ১ ঘণ্টা ফোন ব্যবহার করিনি' },
  { id: 'cl-2', task: 'সকাল ও রাতে পড়ার সময় ১০০% মনোযোগ' },
  { id: 'cl-3', task: 'কলেজে মনোযোগ + নোট সম্পূর্ণ করেছি' },
  { id: 'cl-4', task: 'দিনে ২০ মিনিট ব্যায়াম / হাঁটা' },
  { id: 'cl-5', task: 'অপ্রয়োজনীয় স্ক্রল এড়িয়ে চলেছি' },
  { id: 'cl-6', task: 'রাতে রিফ্লেকশন লিখেছি' },
  { id: 'cl-7', task: 'ঘুমানোর আগে স্ক্রিন অফ ৩০ মিনিট' },
];